import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "About Me",
  description: "Generated by create next app",
};

function page() {
  return (
    <div>
      <h1>Je suis la page About</h1>
    </div>
  );
}

export default page;
